export const GET_BACKLOG_REQUEST = "GET_BACKLOG_REQUEST";
export const GET_BACKLOG_SUCCESS = "GET_BACKLOG_SUCCESS";
export const GET_BACKLOG_FAIL = "GET_BACKLOG_FAIL";

export const GET_PROJECT_TASK_SUCCESS = "GET_PROJET_TASK_SUCCESS";

export const DELETE_PROJECT_TASK = "DELETE_PROJECT_TASK";

export const GET_ERRORS = "GET_ERRORS";
